version: '3.8'
services:
  peer1:
    build:
      context: .
      dockerfile: zona/Dockerfile
    container_name: peer1
    ports:
      - "9090:9090"
      - "8081:8080"
    environment:
      - PEARS=peer2:9090,peer3:9090
      - MY_ADDR=peer1:9090
      - ZONA=NORTE
      - HTTP_PORT=8080
    networks:
      - pbl-network

  peer2:
    build:
      context: .
      dockerfile: zona/Dockerfile
    container_name: peer2
    ports:
      - "9091:9090"
      - "8082:8080"
    environment:
      - PEARS=peer1:9090,peer3:9090
      - MY_ADDR=peer2:9090
      - ZONA=SUL
      - HTTP_PORT=8080
    networks:
      - pbl-network

  peer3:
    build:
      context: .
      dockerfile: zona/Dockerfile
    container_name: peer3
    ports:
      - "9092:9090"
      - "8083:8080"
    environment:
      - PEARS=peer1:9090,peer2:9090
      - MY_ADDR=peer3:9090
      - ZONA=LESTE
      - HTTP_PORT=8080
    networks:
      - pbl-network

  # sensor-norte-1:
  #   build:
  #     context: .
  #     dockerfile: sensores/Dockerfile
  #   environment:
  #     - SENSOR_ID=sensor-norte-1
  #     - ZONA=NORTE
  #     - SERVIDOR=peer1:9090
  #   depends_on:
  #     - peer1
  #   networks:
  #     - pbl-network

#   sensor-sul-1:
#     build:
#       context: .
#       dockerfile: sensores/Dockerfile
#     environment:
#       - SENSOR_ID=sensores-sul-1
#       - ZONA=SUL
#       - SERVIDOR=peer2:9090
#     depends_on:
#       - peer2
#     networks:
#       - pbl-network

#   sensor-leste-1:
#     build:
#       context: .
#       dockerfile: sensores/Dockerfile
#     environment:
#       - SENSOR_ID=sensor-leste-1
#       - ZONA=LESTE
#       - SERVIDOR=peer3:9090
#     depends_on:
#       - peer3
#     networks:
#       - pbl-network

  drone-norte-1:
    build:
      context: .
      dockerfile: drones/Dockerfile
    environment:
      - DRONE_ID=NORTE-drone-01
      - SERVIDOR=peer1:9090
    depends_on:
      - peer1
    networks:
      - pbl-network

  drone-norte-2:
    build:
      context: .
      dockerfile: drones/Dockerfile
    environment:
      - DRONE_ID=NORTE-drone-02
      - SERVIDOR=peer1:9090
    depends_on:
      - peer1
    networks:
      - pbl-network

  drone-norte-3:
    build:
      context: .
      dockerfile: drones/Dockerfile
    environment:
      - DRONE_ID=NORTE-drone-03
      - SERVIDOR=peer1:9090
    depends_on:
      - peer1
    networks:
      - pbl-network
      
networks:
  pbl-network:
    driver: bridge
